=== RackiLovro/WPF-MVVM/HourLogger0/View/db.dtd
<!ELEMENT database (projects, users, departments)>

<!ELEMENT projects (project)*>
<!ELEMENT users (user)*>
<!ELEMENT departments (department)*>

<!ELEMENT project (activity)*>
<!ELEMENT user EMPTY>
<!ELEMENT department EMPTY>

<!ELEMENT activity EMPTY>

<!ATTLIST project projectName CDATA #REQUIRED>
<!ATTLIST user username CDATA #REQUIRED department CDATA #REQUIRED memberSince CDATA #REQUIRED>
<!ATTLIST department departmentName CDATA #REQUIRED>
<!ATTLIST activity duration CDATA #REQUIRED description CDATA #REQUIRED date CDATA #REQUIRED department CDATA #REQUIRED>

=== RackiLovro/WPF-MVVM/HourLogger0/View/database.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE database SYSTEM "db.dtd"[]>
<database>
  <projects>
    <project projectName="WPF">
      <activity description="lovro radi xml" duration="4" date="24.12.2020" department="developeri"/>
    </project>
    <project projectName="C#">
      <activity description="lovro radi c# i update" duration="3" date="25.12.2020" department="developeri"/>
    </project>
  </projects>

  <users>
    <user username="Lovro" memberSince="25.12.2020" department="transformatori"/>
    <user username="Lovro2" memberSince="25.12.2020" department="developeri"/>
  </users>

  <departments>
    <department departmentName="transformatori"/>
    <department departmentName="developeri"/>
  </departments>
</database>

=== RackiLovro/WPF-MVVM/HourLogger0/bin/Debug/database.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE database SYSTEM "db.dtd"[]>
<database>
  <projects>
    <project name="WPFsds">
      <activity description="lovro radi xml" duration="4" date="24.12.2020" department="developeri" />
    </project>
    <project name="C#">
      <activity description="lovro radi c# i update" duration="3" date="23.12.2020" department="developeri" />
    </project>
    <project name="Unesi projektdsad" />
  </projects>
  <users>
    <user username="Lovro" memberSince="25.12.2020" department="transformatori" />
    <user username="Lovro2" memberSince="25.12.2020" department="developeri" />
  </users>
  <departments>
    <department departmentname="transformatori" />
    <department departmentname="developeri" />
  </departments>
</database>
